# ---------------------------| 
GN_option(GN_publicDirs  "public" )
GN_option(GN_privateDirs "private")
GN_option(GN_source_root ${CMAKE_CURRENT_LIST_DIR})


function(init pluginManager)
    GNP_bind(${pluginManager} "unit_constructMetadata" ${GN_source_root}/events.cmake)
    GN_assignFlags("bFlat")
    GN_assignNVal("dirs_public" "dirs_private" "extra_src")
    endfunction()

function(GN_source_onConstruct unit)
    set(publicDirs )
    set(privateDirs)

    GNU_get(root ${unit} "root")
    GNU_getArgs(bFlat ${unit} "bFlat" )
    GNU_getArgs(dirs_public  ${unit} "dirs_public" )
    GNU_getArgs(dirs_private ${unit} "dirs_private")
    GNU_getArgs(extra_src    ${unit} "extra_src"   )
    if (bFlat)
        set(publicDirs ${root})
    else()
        GN_setDefault(dirs_public  ${GN_publicDirs} )
        GN_setDefault(dirs_private ${GN_privateDirs})
        set(publicDirs  ${dirs_public} )
        set(privateDirs ${dirs_private})
        endif()

    set(absPublicDirs )
    set(absPrivateDirs)
    foreach(dir ${publicDirs})
        if (IS_ABSOLUTE ${dir})
            GN_appendList(absPublicDirs "${absPublicDirs}" ${dir})
        else()
            GN_appendList(absPublicDirs "${absPublicDirs}" "${root}/${dir}")
            endif()
        endforeach()
    foreach(dir ${privateDirs})
        if (IS_ABSOLUTE ${dir})
            GN_appendList(absPrivateDirs "${absPrivateDirs}" ${dir})
        else()
            GN_appendList(absPrivateDirs "${absPrivateDirs}" "${root}/${dir}")
            endif()
        endforeach()
    foreach(src ${extra_src})
        if (IS_ABSOLUTE ${src})
            GN_appendList(absPrivateDirs "${absPrivateDirs}" ${src})
        else()
            GN_appendList(absPrivateDirs "${absPrivateDirs}" "${root}/${src}")
            endif()
        endforeach()

    GNU_addSrcType(${unit} "public"  on )
    GNU_addSrcType(${unit} "private" off)
    GNU_addSrcDirs(${unit} "public"  ${absPublicDirs} )
    GNU_addSrcDirs(${unit} "private" ${absPrivateDirs})
    endfunction()
