set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Android CACHE STRING "")
set(ANDROID_NATIVE_API_LEVEL 28 CACHE STRING "")
