macro(event event)
    if    ("${event}" STREQUAL "unit_modifyArguments")
        GN_gtest_modifyArgs(${ARGN})
    elseif("${event}" STREQUAL "unit_constructMetadata")
        GN_gtest_detectTests(${ARGN})
    elseif("${event}" STREQUAL "unit_processSources")
        GN_gtest_addToTests(${ARGN})
    elseif("${event}" STREQUAL "solution_configure")
        GN_gtest_configure()
    elseif("${event}" STREQUAL "solution_configured")
        add_subdirectory(${GN_gtest_proj})
        endif()
    endmacro()
